const stateArray = [
  { name: "alabama", abbreviated: "AL" },
  { name: "alaska", abbreviated: "AK" },
  { name: "arizona", abbreviated: "AZ" },
  { name: "arkansas", abbreviated: "AR" },
  { name: "colorado", abbreviated: "CO" },
  { name: "connecticut", abbreviated: "CT" },
  { name: "delaware", abbreviated: "DE" },
  { name: "florida", abbreviated: "FL" },
  { name: "georgia", abbreviated: "GA" },
  { name: "hawaii", abbreviated: "HI" },
  { name: "idaho", abbreviated: "ID" },
  { name: "illinois", abbreviated: "IL" },
  { name: "indiana", abbreviated: "IN" },
  { name: "iowa", abbreviated: "IA" },
  { name: "kansas", abbreviated: "KS" },
  { name: "kentucky", abbreviated: "KY" },
  { name: "louisiana", abbreviated: "LA" },
  { name: "maine", abbreviated: "ME" },
  { name: "maryland", abbreviated: "MD" },
  { name: "massachusetts", abbreviated: "MA" },
  { name: "michigan", abbreviated: "MI" },
  { name: "minnesota", abbreviated: "MN" },
  { name: "mississippi", abbreviated: "MS" },
  { name: "missouri", abbreviated: "MO" },
  { name: "montana", abbreviated: "MT" },
  { name: "nebraska", abbreviated: "NE" },
  { name: "nevada", abbreviated: "NV" },
  { name: "new hampshire", abbreviated: "NH" },
  { name: "new jersey", abbreviated: "NJ" },
  { name: "new mexico", abbreviated: "NM" },
  { name: "new york", abbreviated: "NY" },
  { name: "north carolina", abbreviated: "NC" },
  { name: "north dakota", abbreviated: "ND" },
  { name: "ohio", abbreviated: "OH" },
  { name: "oklahoma", abbreviated: "OK" },
  { name: "oregon", abbreviated: "OR" },
  { name: "pennsylvania", abbreviated: "PA" },
  { name: "rhode island", abbreviated: "RI" },
  { name: "south carolina", abbreviated: "SC" },
  { name: "south dakota", abbreviated: "SD" },
  { name: "tennessee", abbreviated: "TN" },
  { name: "texas", abbreviated: "TX" },
  { name: "utah", abbreviated: "UT" },
  { name: "vermont", abbreviated: "VT" },
  { name: "virginia", abbreviated: "VA" },
  { name: "washington", abbreviated: "WA" },
  { name: "west virginia", abbreviated: "WV" },
  { name: "wisconsin", abbreviated: "WI" },
  { name: "wyoming", abbreviated: "WY" },
];
